### ISSUE TITLE
"Upload the QR-Code" opens camera instead of File Explorer

### ISSUE THREAD

**Issue by IvanMazzoli** [dgca-verifier/dgca-verifier-webapp#18]
**I expect**
The webapp should open the File Explorer of the phone. Instead, it opens the camera.

**Note**
The problem appears on my Huawei P20 Pro, browser Chrome. I have installed many file explorers

**Comment by kael-k** [comment]
@IvanMazzoli please checkout the PR #20, it should be fixed

**Comment by kael-k** [comment]
@IvanMazzoli, @cifred98 merged the PR which seems to fix the issue on my phone (samsung galaxy A41), could you PTAL? (even on "prod", since it is already merged: https://greenpasschecker.eu/)

**Comment by IvanMazzoli** [comment]
Seems to be working on my new OnePlus 8T, I'll let you know if the bug is still present with my old Huawei

**Comment by kael-k** [comment]
@IvanMazzoli could you provide the android version of the phone?

**Comment by kael-k** [comment]
Also the browser used and its version

**Comment by IvanMazzoli** [comment]
Okay, I tried on both my new and old phones and here are the results:

**Huawei P20 Pro**
The upload button works and shows the page to upload a picture or take a new one, on both cases the image seems **not to be uploaded/checked** most of the times, seems quite unreliable. Have to try on a different network.
**OS:** Android 10
**Browser:** Chrome
**Browser version:** 91.0.4472.120 _can't update to 92.0.4515.115 trough Play Store idk why_

**OnePlus 8T**
The upload button works and shows the page to upload a picture or take a new one, on both cases the image seems **not to be uploaded/checked** most of the times, seems quite unreliable. Have to try on a different network.
**OS:** Android 11
**Browser:** Chrome
**Browser version:** 92.0.4515.115

**Comment by kael-k** [comment]
Sorry @IvanMazzoli for the delayed reply, so the problems seems to be the detection of the QR with the image upload and not anymore the upload mechanism, is that correct?

**Comment by IvanMazzoli** [comment]
Seems so, I have no clue if the image gets actually uploaded

**Comment by kael-k** [comment]
That is strange, may I ask you to try to upload a non QR code image.
For instance, I tried to upload a plate of spaghetti and I get this error.

If the QR is not detected you should get an error like this

![photo_2021-08-12_15-09-46](https://user-images.githubusercontent.com/25031323/129202717-8c95bcba-c00c-4045-b315-5c0cc8c22736.jpg)
